/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedReviewsRouteImport } from './routes/_authenticated/reviews'
import { Route as AuthenticatedProblemsRouteImport } from './routes/_authenticated/problems'
import { Route as AuthenticatedLessonsRouteImport } from './routes/_authenticated/lessons'
import { Route as authLoginRouteImport } from './routes/(auth)/login'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewsRoute = AuthenticatedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProblemsRoute = AuthenticatedProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLessonsRoute = AuthenticatedLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof authLoginRoute
  '/lessons': typeof AuthenticatedLessonsRoute
  '/problems': typeof AuthenticatedProblemsRoute
  '/reviews': typeof AuthenticatedReviewsRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/lessons': typeof AuthenticatedLessonsRoute
  '/problems': typeof AuthenticatedProblemsRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/_authenticated/lessons': typeof AuthenticatedLessonsRoute
  '/_authenticated/problems': typeof AuthenticatedProblemsRoute
  '/_authenticated/reviews': typeof AuthenticatedReviewsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/lessons' | '/problems' | '/reviews'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/lessons' | '/problems' | '/reviews' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/login'
    | '/_authenticated/lessons'
    | '/_authenticated/problems'
    | '/_authenticated/reviews'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/problems': {
      id: '/_authenticated/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof AuthenticatedProblemsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lessons': {
      id: '/_authenticated/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof AuthenticatedLessonsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedLessonsRoute: typeof AuthenticatedLessonsRoute
  AuthenticatedProblemsRoute: typeof AuthenticatedProblemsRoute
  AuthenticatedReviewsRoute: typeof AuthenticatedReviewsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedLessonsRoute: AuthenticatedLessonsRoute,
  AuthenticatedProblemsRoute: AuthenticatedProblemsRoute,
  AuthenticatedReviewsRoute: AuthenticatedReviewsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
